title: Naresh Kumar Devulapally
author: Naresh Devulapally
execute:
  execute_notebooks: "off"

only_build_toc_files: false

html:
  favicon : "figures/TB_favicon.ico"
  baseurl :  "https://naresh-ub.github.io/" #Replace this with your own URL
  extra_css: ["_static/color.css"]

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]
      preexecute: ["thebe-init"] # Automatically execute cells with this tag
    html_theme_options:
      logo:
        text: Naresh Kumar Devulapally
        image_light: figures/naresh-ub.png # Put your logo for the light mode here (can be the same as image_dark)
        image_dark: figures/naresh-ub.png # Put your logo for the dark mode here (can be the same as image_light)
      repository_url: "https://github.com/naresh-ub/naresh-ub.github.io" #add your own repo URL here
      path_to_docs: "book"
      repository_branch: "main"
      use_edit_page_button: false
      use_repository_button: true
      use_issues_button : false
      launch_buttons:
        thebe: true
    html_show_copyright: false
    html_last_updated_fmt: '%B %-d, %Y'
    html_static_path: ["figures"] # add folders that contain files that need to be included, such as the location of the logo(s)
    mathjax3_config:
      chtml: {
        mtextInheritFont: true # To typeset text within math prettier
      }
    # named_colors_include_CSS: true # default value
    # named_colors_dark_and_light: true # default value
    # named_colors_saturation: 1.5 # default value
    # named_colors_custom_colors: None
  extra_extensions:
    - sphinx.ext.imgconverter
    - jupyterbook_patches
    - download_link_replacer
    - sphinx.ext.extlinks
    - sphinx_image_inverter
    - sphinx_iframes
    - sphinx_exercise
    - teachbooks_sphinx_tippy
    - sphinx_named_colors
    # - sphinxcontrib.mermaid
    # - sphinxcontrib.wavedrom
    # - sphinxcontrib.plantuml
    # - sphinxcontrib.tikz
    # - sphinxcontrib.blockdiag

bibtex_bibfiles:
  - references.bib



