title: Naresh Kumar Devulapally
author: Naresh Devulapally

execute:
  execute_notebooks: "off"

only_build_toc_files: false

html:
  favicon: "figures/TB_favicon.ico"
  baseurl: "https://naresh-ub.github.io/"
  extra_css:
    - "_static/color.css"
    - "_static/remotion-embed.css"
  extra_js:
    - "_static/analytics.js"
    - "_static/remotion-embed.js"
  analytics:
    google_analytics_id: G-YTF2311PDM

sphinx:
  config:
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]
      preexecute: ["thebe-init"]
    html_theme_options:
      logo:
        text: Naresh Kumar Devulapally
        image_light: figures/naresh-ub.png
        image_dark: figures/naresh-ub.png
      repository_url: "https://github.com/naresh-ub/naresh-ub.github.io"
      path_to_docs: "book"
      repository_branch: "main"
      use_edit_page_button: false
      use_repository_button: true
      use_issues_button: false
      launch_buttons:
        thebe: true
        colab_url: "https://colab.research.google.com"
      collapse_navigation: true
    html_show_copyright: false
    html_last_updated_fmt: "%B %-d, %Y"
    html_static_path: ["figures", "_static"]
    mathjax3_config:
      chtml:
        mtextInheritFont: true

bibtex_bibfiles:
  - references.bib
