title: Naresh Kumar Devulapally
author: Naresh Devulapally

execute:
  execute_notebooks: "auto"  # Execute notebooks only if source has changed
  # cache: "true"  # Enable caching of notebook outputse

only_build_toc_files: false

html:
  favicon: 
  baseurl: "https://naresh-ub.github.io/"  # Replace this with your own URL
  extra_css: ["_static/color.css"]
  home_page_in_navbar: true
  
sphinx:
  config:
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    sidebar_position: left
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]
      preexecute: ["thebe-init"]  # Automatically execute cells with this tag
    html_theme_options:
      logo:
        text: Naresh Kumar Devulapally
        image_light: figures/naresh-ub.png  # Logo for light mode
        image_dark: figures/naresh-ub.png  # Logo for dark mode
      repository_url: "https://github.com/naresh-ub/naresh-ub.github.io"  # Add your own repo URL here
      path_to_docs: "book"
      repository_branch: "main"
      use_edit_page_button: false
      use_repository_button: true
      use_issues_button: false
      launch_buttons:
        thebe: true
    html_show_copyright: false
    html_last_updated_fmt: '%B %-d, %Y'
    html_static_path: ["figures"]  # Add folders that contain files to be included, such as the location of the logo(s)
    mathjax3_config:
      chtml: {
        mtextInheritFont: true  # To typeset text within math prettier
      }
  extra_extensions:
    - sphinx.ext.imgconverter
    - jupyterbook_patches
    - download_link_replacer
    - sphinx.ext.extlinks
    - sphinx_exercise
    - teachbooks_sphinx_tippy

bibtex_bibfiles:
  - references.bib
